### ISSUE TITLE
Constantly reloading settings

### ISSUE THREAD

**Issue by kapitanluffy** [rexdf/SublimeTextTrans#3]
Is there a way to make it stop reloading the settings?

![image](https://user-images.githubusercontent.com/485799/39808565-d7930adc-53b1-11e8-86cc-1e8a916e9072.png)

**Comment by rexdf** [comment]
Well, my cusom version used to fix this issue. I overwrite it with upstream version.

I will have a look tonight

**Comment by rexdf** [comment]
Every time you click on a new tab or open a new file, it will reloading the settings and set the opacity value.  This behavior is by design. If it does not set the opacity value every time, the transparency will disappear.

**Comment by rexdf** [comment]
If you do want to disable the "reloading" message, you can comment out `reload_settings()`.

It will look like this:

```
...
	class SetOpacityHalfCommand(sublime_plugin.WindowCommand):
		def run(self):
			#reload_settings() #update with user settings, incase user settings was changed
			sublime_opaque(stt_level1)
		def is_checked(self):
			return stt_opacity == stt_level1
....
```

There are 6 class to be changed.

**Comment by rexdf** [comment]
fixed,
